This tutorial covers the following topics:

* Introductions to PyTorch tensors
* Tensor operations and gradients
* Interoperability between PyTorch and Numpy
* How to use the PyTorch documentation site

In [2]:
import torch

## Tensors

At its core, PyTorch is a library for processing tensors. A tensor is a number, vector, matrix, or any n-dimensional array. Let's create a tensor with a single number.

In [3]:
# Number

t1 = torch.tensor(4.)
t1

tensor(4.)

`4.` is a shorthand for `4.0`. It is used to indicate to Python (and PyTorch) that you want to create a floating-point number. We can verify this by checking the `dtype` attribute of our tensor.

In [4]:
t1.dtype

torch.float32

In [5]:
# Vector
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [6]:
# Matrix
t3 = torch.tensor([[5.,6],
                   [7,8],
                   [9,10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [7]:
# 3-dimensional array
t4 = torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

Tensors can have any number of dimensions and different lengths along each dimension. We can inspect the length along each dimension using the `.shape` property of a tensor.

In [8]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [9]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [10]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [11]:
print(t4)
t4.shape

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


torch.Size([2, 2, 3])

## Tensor operations and gradients

We can combine tensors with the usual arithmetic operations. Let's look at an example:

In [12]:
# Create tensors.
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b


(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

We've created three tensors: `x`, `w`, and `b`, all numbers. `w` and `b` have an additional parameter `requires_grad` set to `True`. We'll see what it does in just a moment. 

Let's create a new tensor `y` by combining these tensors.

In [13]:
# Arithmetic Operations
y = x * w + b
y

tensor(17., grad_fn=<AddBackward0>)

As expected, `y` is a tensor with the value `3 * 4 + 5 = 17`. What makes PyTorch unique is that we can automatically compute the derivative of `y` w.r.t. the tensors that have `requires_grad` set to `True` i.e. w and b. This feature of PyTorch is called _autograd_ (automatic gradients).

To compute the derivatives, we can invoke the `.backward` method on our result `y`.

In [14]:
# Compute derivatives
y.backward()

The derivatives of `y` with respect to the input tensors are stored in the `.grad` property of the respective tensors.

In [15]:
# Display Gradients
print('dy/dx', x.grad)
print('dy/dw', w.grad)
print('dy/db', b.grad)

dy/dx None
dy/dw tensor(3.)
dy/db tensor(1.)


As expected, `dy/dw` has the same value as `x`, i.e., `3`, and `dy/db` has the value `1`. Note that `x.grad` is `None` because `x` doesn't have `requires_grad` set to `True`. 

The "grad" in `w.grad` is short for _gradient_, which is another term for derivative. The term _gradient_ is primarily used while dealing with vectors and matrices.

## Tensor Functions
Apart from arithmetic operations, the torch module also contains many functions for creating and manipulating tensors. Let's look at some examples.

In [16]:
# Create a tensor with fixed value for each element
t6 = torch.full((3,2), 42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [17]:
# concatenate two tensors with compatible shape
t7 = torch.cat((t3,t6))
t7

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [18]:
# Compute the sin of each element
t8 = torch.sin(t7)
t8

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [19]:
# Change the shape of tensor
t9 = t8.reshape(3,2,2)
t9

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

In [20]:
t10 = t9.reshape(4,3)
t10

tensor([[-0.9589, -0.2794,  0.6570],
        [ 0.9894,  0.4121, -0.5440],
        [-0.9165, -0.9165, -0.9165],
        [-0.9165, -0.9165, -0.9165]])

## Interoperability with Numpy

[Numpy](http://www.numpy.org/) is a popular open-source library used for mathematical and scientific computing in Python. It enables efficient operations on large multi-dimensional arrays and has a vast ecosystem of supporting libraries, including:

* [Pandas](https://pandas.pydata.org/) for file I/O and data analysis
* [Matplotlib](https://matplotlib.org/) for plotting and visualization
* [OpenCV](https://opencv.org/) for image and video processing


If you're interested in learning more about Numpy and other data science libraries in Python, check out this tutorial series: https://jovian.ai/aakashns/python-numerical-computing-with-numpy .

Instead of reinventing the wheel, PyTorch interoperates well with Numpy to leverage its existing ecosystem of tools and libraries.

In [21]:
# Here's how we create an array in Numpy:
import numpy as np
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [22]:
# Convert the numpy array to a torch tensor
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]])

In [23]:
x.dtype, y.dtype


(dtype('int64'), torch.int64)

In [24]:
# Convert a torch tensor to numpy array
z = y.numpy()
z

array([[1, 2],
       [3, 4]])

The interoperability between PyTorch and Numpy is essential because most datasets you'll work with will likely be read and preprocessed as Numpy arrays.

You might wonder why we need a library like PyTorch at all since Numpy already provides data structures and utilities for working with multi-dimensional numeric data. There are two main reasons:

1. **Autograd**: The ability to automatically compute gradients for tensor operations is essential for training deep learning models.
2. **GPU support**: While working with massive datasets and large models, PyTorch tensor operations can be performed efficiently using a Graphics Processing Unit (GPU). Computations that might typically take hours can be completed within minutes using GPUs.

We'll leverage both these features of PyTorch extensively in this tutorial series.

## Linear Regression with PyTorch


*Linear regression*. We'll create a model that predicts crop yields for apples and oranges (*target variables*) by looking at the average temperature, rainfall and humidity (*input variables or features*) in a region. Here's the training data:

![linear-regression-training-data](https://i.imgur.com/6Ujttb4.png)

In a linear regression model, each target variable is estimated to be a weighted sum of the input variables, offset by some constant, known as a bias :

```
yield_apple  = w11 * temp + w12 * rainfall + w13 * humidity + b1
yield_orange = w21 * temp + w22 * rainfall + w23 * humidity + b2
```

Visually, it means that the yield of apples is a linear or planar function of temperature, rainfall and humidity:

![linear-regression-graph](https://i.imgur.com/4DJ9f8X.png)

The *learning* part of linear regression is to figure out a set of weights `w11, w12,... w23, b1 & b2` by looking at the training data, to make accurate predictions for new data (i.e. to predict the yields for apples and oranges in a new region using the average temperature, rainfall and humidity). This is done by adjusting the weights slightly many times to make better predictions, using an optimization technique called *gradient descent*.

## Training Data

We can represent the training data using two matrices: inputs and targets, each with one row per observation, and one column per variable. 

In [25]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73,67,43],
                   [91,88,64],
                   [87,134,58],
                   [102,43,37],
                   [69,96,70]], dtype='float32')

In [26]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

We've separated the input and target variables, because we'll operate on them separately. Also, we've created numpy arrays, because this is typically how you would work with training data: read some CSV files as numpy arrays, do some processing, and then convert them to PyTorch tensors as follows:

In [27]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs) 
print(targets)


tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


## Linear regression model from scratch

The weights and biases (`w11, w12,... w23, b1 & b2`) can also be represented as matrices, initialized as random values. The first row of `w` and the first element of `b` are used to predict the first target variable i.e. yield of apples, and similarly the second for oranges.

In [28]:
# Weights and biases
w = torch.randn(2, 3, requires_grad = True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-2.0272,  0.7439, -1.9529],
        [-0.4212, -0.0863,  1.8472]], requires_grad=True)
tensor([0.4362, 0.7401], requires_grad=True)


`torch.randn` creates a tensor with the given shape, with elements picked randomly from a [normal distribution](https://en.wikipedia.org/wiki/Normal_distribution) with mean 0 and standard deviation 1.

Our *model* is simply a function that performs a matrix multiplication of the `inputs` and the weights `w` (transposed) and adds the bias `b` (replicated for each observation).


We can define the model as follows:

In [29]:
def model(x):
    return x @ w.t() + b

`@` represents matrix multiplication in PyTorch, and the `.t` method returns the transpose of a tensor.

The matrix obtained by passing the input data into the model is a set of predictions for the target variables.

In [30]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[-181.6803,   43.6402],
        [-243.5582,   73.0380],
        [-189.5108,   59.6699],
        [-246.6063,   22.4124],
        [-204.7257,   92.6980]], grad_fn=<AddBackward0>)


Let's compare the predictions of our model with the actual targets.

In [31]:
# Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


You can see that there's a huge difference between the predictions of our model, and the actual values of the target variables. Obviously, this is because we've initialized our model with random weights and biases, and we can't expect it to *just work*.

## Loss function

Before we improve our model, we need a way to evaluate how well our model is performing. We can compare the model's predictions with the actual targets, using the following method:

* Calculate the difference between the two matrices (`preds` and `targets`).
* Square all elements of the difference matrix to remove negative values.
* Calculate the average of the elements in the resulting matrix.

The result is a single number, known as the **mean squared error** (MSE).

In [32]:
# MSE Loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

`torch.sum` returns the sum of all the elements in a tensor, and the `.numel` method returns the number of elements in a tensor. Let's compute the mean squared error for the current predictions of our model.

In [33]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(43161.1953, grad_fn=<DivBackward0>)


Here’s how we can interpret the result: *On average, each element in the prediction differs from the actual target by about 70.7 (square root of 5004.5132)*. And that’s pretty bad, considering the numbers we are trying to predict are themselves in the range 50–200. Also, the result is called the *loss*, because it indicates how bad the model is at predicting the target variables. Lower the loss, better the model.

## Compute gradients

With PyTorch, we can automatically compute the gradient or derivative of the loss w.r.t. to the weights and biases, because they have `requires_grad` set to `True`.

In [34]:
# Compute gradients
loss.backward()

The gradients are stored in the `.grad` property of the respective tensors. Note that the derivative of the loss w.r.t. the weights matrix is itself a matrix, with the same dimensions.

In [35]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[-2.0272,  0.7439, -1.9529],
        [-0.4212, -0.0863,  1.8472]], requires_grad=True)
tensor([[-24471.3633, -25383.5781, -16072.9668],
        [ -2830.2603,  -3441.0515,  -1911.4135]])


The loss is a [quadratic function](https://en.wikipedia.org/wiki/Quadratic_function) of our weights and biases, and our objective is to find the set of weights where the loss is the lowest. If we plot a graph of the loss w.r.t any individual weight or bias element, it will look like the figure shown below. A key insight from calculus is that the gradient indicates the rate of change of the loss, or the [slope](https://en.wikipedia.org/wiki/Slope) of the loss function w.r.t. the weights and biases.

If a gradient element is **positive**:
* **increasing** the element's value slightly will **increase** the loss.
* **decreasing** the element's value slightly will **decrease** the loss

![postive-gradient](https://i.imgur.com/hFYoVgU.png)

If a gradient element is **negative**:
* **increasing** the element's value slightly will **decrease** the loss.
* **decreasing** the element's value slightly will **increase** the loss.

![negative=gradient](https://i.imgur.com/w3Wii7C.png)

The increase or decrease in loss by changing a weight element is proportional to the value of the gradient of the loss w.r.t. that element. This forms the basis for the optimization algorithm that we'll use to improve our model.

We can subtract from each weight element a small quantity proportional to the derivative of the loss w.r.t. that element to reduce the loss slightly.

In [36]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
print(w)
print(w.grad)
print(b)
print(b.grad)
preds = model(inputs)

tensor([[-1.7825,  0.9978, -1.7922],
        [-0.3929, -0.0519,  1.8664]], requires_grad=True)
tensor([[-24471.3633, -25383.5781, -16072.9668],
        [ -2830.2603,  -3441.0515,  -1911.4135]])
tensor([0.4391, 0.7405], requires_grad=True)
tensor([-289.4163,  -33.7083])


We multiply the gradients with a very small number(10^-5 in this case) to ensure that we don't modify the weights by a very large amount. We want to take a small step in the downhill direction of the gradient, not a giant leap. This number is called the learning rate of the algorithm.

We use torch.no_grad to indicate to PyTorch that we shouldn't track, calculate, or modify gradients while updating the weights and biases.

In [37]:
# Let's verify that the loss is actually lower
loss = mse(preds, targets)
print(loss)

tensor(29275.4277, grad_fn=<DivBackward0>)


Before we proceed, we reset the gradients to zero by invoking the .zero() method. We need to do this because PyTorch accumulates gradients. Otherwise, the next time we invoke .backward on the loss, the new gradient values are added to the existing gradients, which may lead to unexpected results.  

In [38]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


## Train the model using gradient descent

We'll reduce the loss and improve our model using the gradient descent optimization algorithm, which has the following steps:

1. Generate predictions

2. Calculate the loss

3. Compute gradients w.r.t the weights and biases

4. Adjust the weights by subtracting a small quantity proportional to the gradient

5. Reset the gradients to zero

Let's implement the above step by step.

In [39]:
# Generate predictions
preds = model(inputs)
preds

tensor([[-139.8950,   48.8341],
        [-188.6621,   79.8653],
        [-124.8816,   67.8522],
        [-204.7806,   27.4865],
        [-152.2182,   99.2926]], grad_fn=<AddBackward0>)

Note that the predictions are same as before, since we haven't made any changes to our model. The same holds true for the loss and gradients.

In [40]:
# Caluculate the loss
loss = mse(preds, targets)
print(loss)

tensor(29275.4277, grad_fn=<DivBackward0>)


In [41]:
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-20159.7910, -20757.5762, -13216.6289],
        [ -2293.2842,  -2861.7542,  -1554.5695]])
tensor([-238.2875,  -27.3339])


Finally, we update the weights and biases using the gradients computed above.

In [42]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

A few things to note above:

* We use `torch.no_grad` to indicate to PyTorch that we shouldn't track, calculate or modify gradients while updating the weights and biases. 

* We multiply the gradients with a really small number (`10^-5` in this case), to ensure that we don't modify the weights by a really large amount, since we only want to take a small step in the downhill direction of the gradient. This number is called the *learning rate* of the algorithm. 

* After we have updated the weights, we reset the gradients back to zero, to avoid affecting any future computations.

In [43]:
# Let's look at the new weights and biases
print(w)
print(b)

tensor([[-1.5809,  1.2053, -1.6600],
        [-0.3700, -0.0233,  1.8819]], requires_grad=True)
tensor([0.4414, 0.7407], requires_grad=True)


In [44]:
# With the new weights and biases, the model should have lower loss.
preds = model(inputs)
loss = mse(preds , targets)
print(loss)

tensor(19916.5039, grad_fn=<DivBackward0>)


We have already achieved a significant reduction in the loss, simply by adjusting the weights and biases slightly using gradient descent.

## Train for multiple epochs

To reduce the loss further, we can repeat the process of adjusting the weights and biases using the gradients multiple times. Each iteration is called an epoch. Let's train the model for 100 epochs.

In [45]:
# Train for multiple epochs 
for i in range(2000):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [46]:
# Once again, let's verify that the loss is now lower
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(6.5782, grad_fn=<DivBackward0>)


As you can see, the loss is now much lower than what we started out with. Let's look at the model's predictions and compare them with the targets.

In [47]:
# Predictions
preds

tensor([[ 57.4939,  70.2823],
        [ 80.0493, 101.8506],
        [123.0730, 130.3192],
        [ 22.3020,  36.2662],
        [ 97.5461, 121.7734]], grad_fn=<AddBackward0>)

In [48]:
# Targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

The prediction are now quite close to the target variables, and we can get even better results by training for a few more epochs. 

## Linear regression using PyTorch built-ins

The model and training process above were implemented using basic matrix operations. But since this such a common pattern , PyTorch has several built-in functions and classes to make it easy to create and train models.

Let's begin by importing the `torch.nn` package from PyTorch, which contains utility classes for building neural networks.

In [49]:
import torch.nn as nn

In [50]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], 
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], 
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

## Dataset and DataLoader

We'll create a `TensorDataset`, which allows access to rows from `inputs` and `targets` as tuples, and provides standard APIs for working with many different types of datasets in PyTorch.

In [51]:
from torch.utils.data import TensorDataset

In [52]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

The `TensorDataset` allows us to access a small section of the training data using the array indexing notation (`[0:3]` in the above code). It returns a tuple (or pair), in which the first element contains the input variables for the selected rows, and the second contains the targets.

We'll also create a `DataLoader`, which can split the data into batches of a predefined size while training. It also provides other utilities like shuffling and random sampling of the data.

In [53]:
from torch.utils.data import DataLoader

In [54]:
# Define batch loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)


In [55]:
# The data loader is typically used in a for-loop.

for xb, yb in train_dl:
    print(xb)
    print(yb)
    break 

tensor([[102.,  43.,  37.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [ 73.,  67.,  43.],
        [ 87., 134.,  58.]])
tensor([[ 22.,  37.],
        [ 81., 101.],
        [119., 133.],
        [ 56.,  70.],
        [119., 133.]])


In each iteration, the data loader returns one batch of data, with the given batch size. If `shuffle` is set to `True`, it shuffles the training data before creating batches. Shuffling helps randomize the input to the optimization algorithm, which can lead to faster reduction in the loss.

## nn.Linear

Instead of initializing the weights & biases manually, we can define the model using the `nn.Linear` class from PyTorch, which does it automatically.

In [56]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.4793,  0.3200, -0.5506],
        [-0.1929, -0.0755,  0.0611]], requires_grad=True)
Parameter containing:
tensor([-0.3751,  0.0699], requires_grad=True)


PyTorch models also have a helpful `.parameters` method, which returns a list containing all the weights and bias matrices present in the model. For our linear regression model, we have one weight matrix and one bias matrix.

In [57]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[ 0.4793,  0.3200, -0.5506],
         [-0.1929, -0.0755,  0.0611]], requires_grad=True),
 Parameter containing:
 tensor([-0.3751,  0.0699], requires_grad=True)]

In [58]:
# We can use the model to generate predictions in the same exact way as before:
preds = model(inputs)
preds

tensor([[ 32.3779, -16.4462],
        [ 36.1625, -20.2215],
        [ 52.2686, -23.2900],
        [ 41.9021, -20.5958],
        [ 24.8737, -16.2143],
        [ 32.3779, -16.4462],
        [ 36.1625, -20.2215],
        [ 52.2686, -23.2900],
        [ 41.9021, -20.5958],
        [ 24.8737, -16.2143],
        [ 32.3779, -16.4462],
        [ 36.1625, -20.2215],
        [ 52.2686, -23.2900],
        [ 41.9021, -20.5958],
        [ 24.8737, -16.2143]], grad_fn=<AddmmBackward0>)

## Loss Function

Instead of defining a loss function manually, we can use the built-in loss function `mse_loss`.

In [59]:
# Import nn.functional
import torch.nn.functional as F

The `nn.functional` package contains many useful loss functions and several other utilities. 

In [60]:
# Define loss function
loss_fn = F.mse_loss

In [61]:
# Let's compute the loss for the current predictions of our model
loss  = loss_fn(model(inputs), targets)
print(loss)

tensor(8171.5645, grad_fn=<MseLossBackward0>)


## Optimizer

Instead of manually manipulating the model's weights & biases using gradients, we can use the optimizer `optim.SGD`. SGD stands for `stochastic gradient descent`. It is called `stochastic` because samples are selected in batches (often with random shuffling) instead of as a single group.

In [62]:
# Define Optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

Note that `model.parameters()` is passed as an argument to `optim.SGD`, so that the optimizer knows which matrices should be modified during the update step. Also, we can specify a learning rate which controls the amount by which the parameters are modified.

## Train the model

We are now ready to train the model. We'll follow the exact same process to implement gradient descent:

1. Generate predictions

2. Calculate the loss

3. Compute gradients w.r.t the weights and biases

4. Adjust the weights by subtracting a small quantity proportional to the gradient

5. Reset the gradients to zero

The only change is that we'll work batches of data, instead of processing the entire training data in every iteration. Let's define a utility function `fit` which trains the model for a given number of epochs.

In [63]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

Some things to note above:

* We use the data loader defined earlier to get batches of data for every iteration.

* Instead of updating parameters (weights and biases) manually, we use `opt.step` to perform the update, and `opt.zero_grad` to reset the gradients to zero.

* We've also added a log statement which prints the loss from the last batch of data for every 10th epoch, to track the progress of training. `loss.item` returns the actual value stored in the loss tensor.

Let's train the model for 100 epochs.

In [64]:
fit(100, model, loss_fn, opt)

Epoch [10/100], Loss: 441.5833
Epoch [20/100], Loss: 123.5054
Epoch [30/100], Loss: 321.6271
Epoch [40/100], Loss: 81.9430
Epoch [50/100], Loss: 67.9015
Epoch [60/100], Loss: 104.2600
Epoch [70/100], Loss: 85.2313
Epoch [80/100], Loss: 36.1920
Epoch [90/100], Loss: 46.6195
Epoch [100/100], Loss: 39.8256


In [65]:
fit(100, model, loss_fn, opt)

Epoch [10/100], Loss: 70.5849
Epoch [20/100], Loss: 64.0016
Epoch [30/100], Loss: 18.6993
Epoch [40/100], Loss: 36.7569
Epoch [50/100], Loss: 15.9058
Epoch [60/100], Loss: 41.9096
Epoch [70/100], Loss: 43.6026
Epoch [80/100], Loss: 24.4305
Epoch [90/100], Loss: 21.0103
Epoch [100/100], Loss: 30.8559


In [66]:
# Generate Predictions
preds = model(inputs)
preds

tensor([[ 57.7387,  70.6416],
        [ 77.9349,  98.8507],
        [127.0600, 136.4191],
        [ 24.6502,  38.7845],
        [ 92.3624, 114.9649],
        [ 57.7387,  70.6416],
        [ 77.9349,  98.8507],
        [127.0600, 136.4191],
        [ 24.6502,  38.7845],
        [ 92.3624, 114.9649],
        [ 57.7387,  70.6416],
        [ 77.9349,  98.8507],
        [127.0600, 136.4191],
        [ 24.6502,  38.7845],
        [ 92.3624, 114.9649]], grad_fn=<AddmmBackward0>)

In [67]:
# Compare wiht targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

Indeed, the predictions are quite close to our targets, and now we have a fairly good model to predict crop yields for apples and oranges by looking at the average temperature, rainfall and humidity in a region. We can use it to make predictions of crop yields for new regions by passing a batch containing a single row of input.

In [68]:
model(torch.tensor([[75, 63, 44.]]))

tensor([[53.1204, 67.3073]], grad_fn=<AddmmBackward0>)

## Machine learning essence
In this Notebook, we've defined a "model" that assumes a specific relationship between the inputs and the outputs, expressed using some unknown parameters (weights & biases). We then show the model some known inputs and outputs and train the model to come up with good values for the unknown parameters. Once trained, the model can be used to compute the outputs for new inputs.

This paradigm of programming is known as machine learning, where we use data to figure out the relationship between inputs and outputs. Deep learning is a branch of machine learning that uses matrix operations, non-linear activation functions and gradient descent to build and train models.

## Converting a linear regression model into a basic deep learning model

In [70]:
model2 = nn.Sequential(
    nn.Linear(3,3),
    nn.Sigmoid(),
    nn.Linear(3,2)  
)

In [98]:
opt = torch.optim.SGD(model2.parameters(), lr=1e-2)
fit(300, model2, F.mse_loss, opt)

Epoch [10/300], Loss: 2082.9165
Epoch [20/300], Loss: 1115.2686
Epoch [30/300], Loss: 1584.7620
Epoch [40/300], Loss: 1785.2461
Epoch [50/300], Loss: 1115.4426
Epoch [60/300], Loss: 757.1500
Epoch [70/300], Loss: 1253.2422
Epoch [80/300], Loss: 615.7513
Epoch [90/300], Loss: 968.8008
Epoch [100/300], Loss: 2186.6877
Epoch [110/300], Loss: 727.0856
Epoch [120/300], Loss: 1273.1611
Epoch [130/300], Loss: 1535.6072
Epoch [140/300], Loss: 1272.9822
Epoch [150/300], Loss: 1191.8811
Epoch [160/300], Loss: 1325.0037
Epoch [170/300], Loss: 1535.0974
Epoch [180/300], Loss: 1461.8749
Epoch [190/300], Loss: 1191.8800
Epoch [200/300], Loss: 1252.8087
Epoch [210/300], Loss: 687.4174
Epoch [220/300], Loss: 1191.8823
Epoch [230/300], Loss: 756.2402
Epoch [240/300], Loss: 1191.8800
Epoch [250/300], Loss: 1535.2078
Epoch [260/300], Loss: 2039.8232
Epoch [270/300], Loss: 1058.7007
Epoch [280/300], Loss: 1701.6855
Epoch [290/300], Loss: 1333.8772
Epoch [300/300], Loss: 1191.8799


### Feedfoward Neural Network

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Multi-Layer_Neural_Network-Vector-Blank.svg/400px-Multi-Layer_Neural_Network-Vector-Blank.svg.png"
     style="background:white; padding:8px; border-radius:4px;" />


Conceptually, you think of feedforward neural networks as two or more linear regression models stacked on top of one another with a non-linear activation function applied between them.

<img src="https://cdn-images-1.medium.com/max/1600/1*XxxiA0jJvPrHEJHD4z893g.png" width="640">

To use a feedforward neural network instead of linear regression, we can extend the `nn.Module` class from PyTorch.